version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: constructs
    versions:
    - 3.2.117
    - 3.3.12
    - 3.3.14
    - 3.3.16
    - 3.3.17
    - 3.3.18
    - 3.3.20
    - 3.3.21
    - 3.3.22
    - 3.3.24
    - 3.3.27
    - 3.3.29
    - 3.3.3
    - 3.3.32
    - 3.3.36
    - 3.3.41
    - 3.3.43
    - 3.3.48
    - 3.3.5
    - 3.3.50
    - 3.3.54
    - 3.3.58
    - 3.3.61
    - 3.3.62
    - 3.3.65
    - 3.3.68
    - 3.3.71
    - 3.3.74
    - 3.3.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: jsii
    versions:
    - 1.19.0
